/* Generated by YAKINDU Statechart Tools for Arduino v0.4.0 */

#include "ArduinoMain.h"
#include "ATmega_Timer1.h"
#include "../src/WindowAutomationConnector.h"

#define CYCLE_PERIOD 10
#define MAX_PARALLEL_TIMERS 0

WindowAutomation* statemachine;
WindowAutomationConnector* connector;
ATmega_Timer1* timer;

WindowAutomation* getStatemachine(){
	return statemachine;
}

void setup() {
	statemachine = new WindowAutomation();
	connector = new WindowAutomationConnector(statemachine);
	timer = new ATmega_Timer1(statemachine, connector, MAX_PARALLEL_TIMERS, CYCLE_PERIOD);

}

void loop() {
	timer->runCycle();
}
