/* Generated by YAKINDU Statechart Tools for Arduino v0.4.0 */

#ifndef ARDUINOMAIN_H
#define ARDUINOMAIN_H

#include <Arduino.h>
#include "WindowAutomation.h"

WindowAutomation* getStatemachine();

#endif /* ARDUINOMAIN_H */
