/* Generated by YAKINDU Statechart Tools for Arduino v0.4.0 */

#ifndef TIMEEVENT_H
#define TIMEEVENT_H

#include "TimedStatemachineInterface.h"

class TimeEvent {

public:
	TimedStatemachineInterface *timedStatemachine;
	sc_eventid eventId;
	sc_boolean periodic;
	unsigned int overflows;
	unsigned int overflowCounter;
	bool eventRaised;
};

#endif /* TIMEEVENT_H */
